---
- name: Create pods using deployment 
  hosts: all
  become: true
  tasks: 
  - name: copy files
    copy: src=/home/renga5/workspace/task/ dest=/home/renga5/
  - name: create a deployment
    command: sudo kubectl create -f /home/renga5/nginx.yaml
  - name: service for kubernetes
    command: sudo kubectl create -f /home/renga5/service-pod.yaml
