---
- name: Create pods using deployment 
  hosts: all
  become: true
  tasks: 
  - name: copy files
    copy: src=/home/renga5/workspace/moniotring/ dest=/home/renga5/renga/
  - name: create a deployment
    command: sudo kubectl create -f /home/renga5/renga/clusterRole.yaml
  - name: service for kubernetes
    command: sudo kubectl create -f /home/renga5/renga/config-map.yaml
